### ISSUE TITLE
Editor behaves odd on import

### ISSUE THREAD

**Issue by sbarwe** [PKGeorgiev/node-red-contrib-message-counter#1]
On node 0.17 it does not work
The node is doubled
![image](https://cloud.githubusercontent.com/assets/17012408/25744206/df24024c-3198-11e7-9f8e-a6ac68dcca09.png)

Getting the following exception in the editor
`
red.js:9729 Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
`

<details>

    at updateSelection (http://localhost:1880/red/red.js:9729:34)
    at HTMLDivElement.drop (http://localhost:1880/red/red.js:8979:17)
    at e.(anonymous function).(anonymous function)._trigger (http://localhost:1880/vendor/vendor.js:16:10003)
    at e.(anonymous function).(anonymous function)._drop (http://localhost:1880/vendor/vendor.js:16:40380)
    at e.(anonymous function).(anonymous function)._drop (http://localhost:1880/vendor/vendor.js:16:5029)
    at e.(anonymous function).(anonymous function).<anonymous> (http://localhost:1880/vendor/vendor.js:16:42279)
    at Function.each (http://localhost:1880/vendor/vendor.js:2:2975)
    at Object.drop (http://localhost:1880/vendor/vendor.js:16:42092)
</details>

`
red.js:9729 Uncaught TypeError: Converting circular structure to JSON`
<details>
 
    at JSON.stringify (<anonymous>)
    at updateSelection (red.js:9729)
    at SVGGElement.canvasMouseDown (red.js:9116)
    at SVGGElement.i [as __onmousedown] (vendor.js:32)

</details>

**Comment by PKGeorgiev** [comment]
Hi @sbarwe , 
Can you clarify your Node-red & Node JS & browser versions?

**Comment by sbarwe** [comment]
Hi, node 7, node red 0.17 (from git) , latest chrome
(all windows 10 x64)
